openapi: 3.0.1
paths:
  /backForIt:
    get:
      operationId: index
      responses:
        "200":
          description: index 200 response
          content:
            text/plain:
              schema:
                type: string
  /booking:
    get:
      operationId: getBookings
      responses:
        "200":
          description: getBookings 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Booking"
  /booking/check:
    get:
      operationId: checkAvailability
      responses:
        "200":
          description: checkAvailability 200 response
          content:
            text/plain:
              schema:
                type: string
  /booking/new:
    post:
      operationId: newBooking
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Booking"
        required: true
      responses:
        "200":
          description: newBooking 200 response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Booking"
components:
  schemas:
    Booking:
      type: object
      properties:
        endDate:
          type: string
        guestId:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
          nullable: true
        roomId:
          type: integer
          format: int64
        startDate:
          type: string
